### PR TITLE
refactor: localhost deployments with new infra

### PR DESCRIPTION
**Pull request by iadjadj**

### CODE REVIEW

**Review by lzianekhodja — DISMISSED** [review]

**Comment by lemaitre-aneo** [comment]
This does not include AWS deployment, and multistage deployment. Is this expected?

**Comment by lemaitre-aneo** [comment]
This does not include AWS deployment, and multistage deployment. Is this expected?

**Comment by lzianekhodja** [comment]
He is going to make other PRs for each deployment. It is easier to review them (especially those on AWS)
We will not merge this one immediately.

**Review by lemaitre-aneo — APPROVED** [review]
C'est bon pour moi, par contre le titre n'est pas bon. C'est pas all-in-one, mais multi-stage.

**Review by lzianekhodja — APPROVED** [review]

**Pull request merged**
